app/nginx_location.conf

When using basic auth https://github.com/jwilder/nginx-proxy#basic-authentication-support,
letsencrypt can't verify the challenge and certificate creation fails. basic auth needs to be switched off for the .well-known directory

Disable basic auth for letsencrypt challenge

---

README.md

Simple fix, but if you read things a little too literally like I did... you can get tripped up. :-)

Fix typo in environment variable

---

app/letsencrypt_service

cert.pem is needed for other services like postfix

Create cert.pem in Response to #22

---

app/nginx_location.conf

Add a break into the letsencrypt block so that no more rules are executed otherwise if you have a block like...
location /.well-known/acme-challenge/ {
auth_basic off;
root /usr/share/nginx/html;
try_files $uri =404;
}
if (!-f /code/home/cookies/$cookie_AUTH_COOKIE) {
rewrite ^ https://auth.example.org break;
}
Then lets encrypt never manages to verify the domain as the request gets re-written to the authentication URL and you get messages like...
Creating/renewal blah.example.org certificates... (blah.example.org)
2016-05-06 13:02:36,270:INFO:simp_le:1211: Generating new account key
2016-05-06 13:02:36,822:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-05-06 …

break in location in case the upstream is protected

---

app/nginx_location.conf

Enable public access to validation endpoints despite existing IP whitelisting or basic auth settings. For existing basic auth and IP whitelist setups, the `auth_basic off;` is not sufficient to allow Lets Encrypt to be able to access the container via HTTP.

enable public access to validation endpoints

---

app/entrypoint.sh

Assuming they're following a conventional setup, this will warn users
that they likely didn't set their volumes up correctly. It's not an
error though because they may have done something like mount the entire
/etc/nginx directory.

Warn if volumes don't appear to be setup correctly

---

app/letsencrypt_service
install_simp_le.sh

SAN certificates are now only created if the domain is contained in the base_domain.
For example:
`LETSENCRYPT_HOST=domain.tld,sub.domain.tld,sub2.domain.tld,newdomain.tld,sub.newdomain.tld`
will create 2 SAN certificates for `domain.tld` and `newdomain.tld`.

[FEATURE] Create SAN certificates only for common domains

---

app/functions.sh

Based on the docker issue (https://github.com/docker/docker/issues/26099) the docker api needs to be called with `localhost` in the URL. With earlier versions of curl this wasn't an issue, starting with curl 7.5 an error is returned. Adding localhost works for newer and older versions of curl.

Update docker API call

---

app/nginx_location.conf

In nginx.tmpl, when you want to renew, vhosts.d that contains our 'location /.well-known/...' directive is included before the 'location /' target, and last one seems to bypass our LE location.
If our /.well-known location is defined as a prefix string (or as a regex), it takes priority over basic locations
Details on http://nginx.org/en/docs/http/ngx_http_core_module.html#location

Set /.well-known/acme-challenge nginx location path as prefix string

---

app/letsencrypt_service_data.tmpl

My need is to ignore the containers which have LETSENCRYPT_HOST environment variable, but it's empty. Currently in this case the following error is displayed every second, in a loop:
Creating/renewal  certificates... ()
simp_le: error: argument -d/--vhost: expected one argument
/app/letsencrypt_service: line 18: 1: missing base_domain argument
Creating/renewal  certificates... ()
simp_le: error: argument -d/--vhost: expected one argument
/app/letsencrypt_service: line 18: 1: missing base_domain argument
I want to start applications via Docker Compose, and pass LETSENCRYPT_HOST variable from the environment, and if the variable is not present when running docker-compose, then I want to not activate Let's Encrypt for this application. 
Example docker-compose.yml:
version: '2'
services: …

Do not generate certs if LETSENCRYPT_HOST is empty

---

README.md
app/entrypoint.sh

Fixes https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/170

Get nginx container id from labelled container

---

install_simp_le.sh

[kuba/simp_le](https://github.com/kuba/simp_le) have been abandoned by its author a year ago and hasn't been maintained since.
[zenhack's fork](https://github.com/zenhack/simp_le) appears to be the most actively maintained one.

switch to zenhack/simp_le

---

README.md
app/functions.sh

As described in issue #121 there is a bug when there is no new domains added, and needed to _SIGHUP_ _nginx_ container.
This pull requests automatize this reload in this case scenario.
It could be more optimal and only reload _nginx_ container in case no new domains had been found, but sending _SIGHUP_ to _nginx_ container twice doesn't seem like a big cost. At least for a quick short term solution.

Fix renewals on separate containers

---

README.md
app/letsencrypt_service
app/letsencrypt_service_data.tmpl

I've added support to choose the key size of the keys/certificates letsencrypt-companion requests. NGINX does not have a problem with the default key size of 4096 bit, but other services like the cyrus imap server do not accept such large keys.
I would appreciate if you could merge my addition into your codebase, so I and (hopefully) other people can benefit from it in the future.
Thank you very much!

Added support for choosing a certain key size via environment variable 'LETSENCRYPT_KEYSIZE'.

---

README.md

Hi there!
Thanks for the good work and I would like to share a new sample.
Cheers!

Update readme with sample using docker-compose version '3'

---

README.md
app/letsencrypt_service

This enable the use of simp_le `--reuse_key` option via the new environment variable `REUSE_KEY`
Reusing the previous private key at certificate renewal instead of generating a new one is almost mandatory if you want to setup things like [HPKP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning), as outlined in #217 
This commit has been tested on a real setup and is working as intended.

enable simp_le private key reutilisation

---

README.md
app/entrypoint.sh
app/functions.sh

This is my attempt to solve the same #205 issue.
In Swarm Mode and Docker Cloud, container names are dynamic. #181 solved this partially with a label on `jwilder/nginx-proxy` but not if they're separate containers. #126 tries a different approach, but I think using a label is a better one.
This PR simply adds a `com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen=true` label to the docker-gen container.
It also moves the label related detection to runtime (functions.sh: nginx-reload) instead of startup time (entrypoint.sh), because the nginx and docker-gen containers could be redeployed during the lifecycle of the letsencrypt companion, and thus, getting different ids.
There's also a new assumption in that I think it's simpler to just recommend using the label instead of …

Complete support for dynamic container names

---

app/nginx_location.conf

As suggested in #112 
`/.well-known/acme-challenge` is indeed unreachable if `basic_auth` has been enabled on the nginx proxy container.
Tested and working as intended.

Disable auth for the acme-challenge location

---

README.md
app/force_renew
app/letsencrypt_service

This PR add a `force_renew` script in the /app folder.
The script force the renewal of all existing certificates via the `--valid_min` argument of `simp_le` (asking for a minimum validity of 90 days, which for LE certificates means they'll be renewed no matter what).

Add the ability to force the renewal of all certificates

---

app/letsencrypt_service

Forced renewal with `/app/force_renew` currently renew only the first certificate it find on `letsencrypt_service_data` due to a `&& shift` that should not have been there in the first place (my mistake entirely).
@JrCs > could you please merge this as soon as convenient for you ? This feature is really needed for troubleshooting.

Fix forced renewal of certificates

---

app/letsencrypt_service
install_simp_le.sh

This PR fixes #277 (which is another iteration of #90).
It also removes reliance on a harcoded Let's Encrypt ToS hash, as `simp_le` version 0.6.2 is now able to retrieve the latest LE ToS's hash by itself. This prevents the same breakage to happen again when the LE ToS are modified.

Fix TOS hash mismatch breakage

---

README.md

Documentation was unclear regarding statically named contains and where the environment variables went.

Add example for static names in README.md

---

.travis.yml
README.md
tests/after-failure.sh
tests/setup-boulder.sh
tests/setup-nginx-proxy.sh
tests/test-functions.sh
tests/test.sh

This PR adds a base Travis CI test suite to the project.
It is crude and does not yet test for every options but crude tests are better than no test.

Add Travis CI automated testing

---

Dockerfile
app/entrypoint.sh
app/functions.sh
app/letsencrypt_service
app/start.sh
app/update_certs

This PR:
- provides a bit of shell linting (with [shellcheck](https://github.com/koalaman/shellcheck)).
- fix `update_certs` so that it works both with `procps`'s and `busybox`'s versions of `pkill`.
- updates the base image from `alpine:3.3` to `alpine:3.6` (required the former point to work).
- replace the deprecated `MAINTAINER` statement with `LABEL maintainer`.
- removes `procps` package as it does not provide `pkill` as of `alpine:3.4`.
- removes `tar` package as it is included in alpine (provided by `busybox`).
- adds `openssl` package as it is a runtime dependency of `simp_le` and was previously installed as a dependency of `curl` (that's no longer the case in `alpine:3.6`).
- prettify and streamline the Dockerfile.

Update base image to Alpine 3.6

---

app/letsencrypt_service
app/letsencrypt_service_data.tmpl

This fix safeguard against potential attempted forced deletions of `/etc/nginx/certs` when trying to do `rm -rf /etc/nginx/certs/$var` with a `var` that is empty or contains only spaces.
See #288

Do not rm -rf with a trailing empty var

---

README.md

The docker environment variables in readme appear to be reversed.

Correct typo in parameter documentation

---

README.md

Peoples seems to often run into misconfiguration issues with this method.

Do not tag separate containers as recommended

---

README.md
app/letsencrypt_service
app/letsencrypt_service_data.tmpl

In addition to the improved handling of ACME account keys decribed in #291 , this PR:
- change the name of env var `REUSE_KEY` to `REUSE_PRIVATE_KEYS` to avoid confusion with the new `REUSE_ACCOUNT_KEYS`environment variable.
- make the the container behave the same when you set `LETSENCRYPT_TEST` to `true` on a proxyed container and when you set the `ACME_CA_URI `environment variable to the Let's Encrypt staging api endpoint. Previously certs generated when explicitly using the LE stating api endpoint where not really considered test certificates by the container.
- avoids `--email` being passed to `simp_le` with no address when `LETSENCRYPT_EMAIL`is not set, making the contact email truly optional (and preventing issues like #263)
- update the doc to take all that into account and add …

Merge dev into master

---

app/letsencrypt_service

Fix for issue #351, prevents accidental deletion of custom certificates.
A version containing this fix has been pushed as `latest` and `v1.8` on DockerHub.

Fix unwanted custom cert removal #351

---

app/nginx_location.conf

This is a small change to make the matching a little bit faster, while also allowing more general blocking.
First some reference to the docs.
> If the longest matching prefix location has the “^~” modifier then regular expressions are not checked. 
[Nginx http_core_module](https://nginx.org/en/docs/http/ngx_http_core_module.html#location)
Further, from the docs, the evaluation order is the following;
1. Exact matches (using the = modifier)
2. Implicit prefix matching(no modifier or ^~)
3. Regex(~ and ~*)
As such, without a modifier(such as ^~), the location directive matches with the prefix of the challenge address, but can be overridden by a subsequent regex directive. An example is a general regex block for dot-files and dot-folders, such as this example taken from nextcloud;
> location …

Add ^~ to location directive

---

test/README.md

Erroneous underscores in the container name replaced with dashes.

Test README typos

---

.travis.yml
test/run.sh
test/setup/setup-boulder.sh
test/setup/setup-local.sh
test/tests/test-functions.sh

[Recent changes](https://github.com/letsencrypt/boulder/pull/3679) to boulder's `docker-compose.yml` file broke the test suite.
This PR fix Boulder setup and integration tests with the current version of Boulder.

Fix test suite breakage due to boulder update

---

test/README.md
test/run.sh
test/setup/setup-boulder.sh
test/setup/setup-local.sh

This PR enable local testing on macOS by taking into account minor differences with `sed`, `getopt` and `bash` versions packaged with this OS.
I had to reverted `10.77.77.1` to `localhost` in `test/setup/setup-boulder.sh`, as using the Docker gateway IP to curl Boulder's ACME endpoint from macOS Terminal does not appear to work.

Enable tests on macOS

---

app/letsencrypt_service

In addition to https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/pull/352, I would suggest to keep untouched symlinks to disabled domains, if the certificate does not belong to Letsencrypt.
As a use case example, say I have many `example.com` subdomains and a wildcard certificate `wild.example.com.crt` under `example.com` directory. So I do:
```bash
ln -s example.com/wild.example.com.crt subdomain.example.com.crt
ln -s example.com/wild.example.com.crt otherdomain.example.com.crt
```
and so on. In this case I would not like to see my symlinks removed because they are not created by this proxy companion.

Prevent non-Letsencrypt certs removing

---

install_simp_le.sh

`simp_le` version bump.
Nothing groundbreaking in this version other than fixing the deprecation warning reported in #370

Update simp_le to 0.8.0

---

app/entrypoint.sh
app/functions.sh

This is a fix for #375
This PR move the self ID retrieval to a reusable function, instead of a one time operation that stores the ID in an environment variable at container startup.
The `/app/force_renew` script  being used through `docker exec`, it can't access this environment variable and therefore fails to check for a running nginx container (#321) when using the `--volumes-from` method.

Move the self ID retrieval to /app/functions.sh

---

app/letsencrypt_service

Follow-up to #379
@buchdag in the previous pull request the `certfile` variable did not contain the full path to cert, so the patch was pretty useless. This pull request is checked better and fixes my mistake.

Fixed path to certfile, added debug echos

---

.gitignore
test/setup/setup-nginx-proxy.sh
test/tests/docker_api/run.sh
test/tests/test-functions.sh

Due to a misspelling of `expected-std-out.txt`, the existing test script was actually testing pretty much nothing.
The test has been extended to cover the nine possible mix of `--volumes-from`, environment variables and docker labels.

Fix and extend the docker_api test unit

---

app/entrypoint.sh

As proposed here https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/319#issuecomment-384178784, this adds an explicit error during initialisation if `ACME_CA_URI` is an unsupported -by `simp_le`- Let's Encrypt ACME v2 endpoint.

Check for unsupported ACME v2 LE endpoints

---

Dockerfile

https://docs.docker.com/develop/develop-images/multistage-build/
This Dockerfile does not fetch a pre built binary of `docker-gen` like the current one but compile it from source during the first stage, then grab the compiled binary for the final image from this stage.
This allows to build the image on any arch the `golang` and `alpine` images are available for from a single Dockerfile.
Tested and working on `arm` 32 bits arch (Raspbian running on  a Raspberry Pi 3).
I feel this is a cleaner and more flexible solution than the usual method of maintaining a different Dockerfile for each arch (as proposed in #372). The drawbacks are:
- requires Docker 17.05+ to build
- the intermediate stage containers have to be manually cleaned

Use multi-stage build

---

app/entrypoint.sh

Like the other `entrypoint.sh` checks, this one is only wanted once, during container initialization.

Check deprecated env var at container init only

---

app/functions.sh

Output a different message when the `check_nginx_proxy_container_run` function can't get any container ID, rather than than a message with no container ID.

Error message enhancement to #321

---

app/functions.sh
test/tests/docker_api/run.sh

The /app/docker-entrypoint.sh within nginx-proxy [sets the RESOLVERS environment variable](https://github.com/jwilder/nginx-proxy/blob/master/docker-entrypoint.sh#L22), so when docker-proxy is invoked without it the resolvers aren't set in the nginx config.
The more general problem, which this PR doesn't fix, is that all other environment variables are also clobbered when the config is generated by these means.
Unfortunately, as docker-gen is run via forego within docker-proxy, a HUP signal sent to the docker-proxy container won't be passed through (it just kills the container). I think the actual fix here is probably to change the handling of HUP's within forego?
Might also be worth a note in the README as it took me ages to work out why this environment variable seemed not to be set …

invoke /app/docker-entrypoint.sh when reloading nginx-proxy

---

app/entrypoint.sh

As requested by @NicolasDorier [here](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/pull/394#discussion_r195306446).

Compare DH param with sha256 instead of md5

---

app/functions.sh

Going through /app/docker-entrypoint.sh in the nginx-proxy container generate some unwanted garbage to std out:
```
nginx-proxy-le | 
nginx-proxy-le | 
nginx-proxy-le | 
nginx-proxy-le | 
nginx-proxy-le | 
nginx-proxy-le | 
nginx-proxy-le | 2Custom dhparam.pem file found, generation skipped
nginx-proxy-le | 
nginx-proxy-le | 
nginx-proxy-le | 
nginx-proxy-le | 
nginx-proxy-le | 
nginx-proxy-le | 
nginx-proxy-le | h2018/06/14 16:03:18 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx-proxy-le | 
nginx-proxy-le | 
nginx-proxy-le | 
nginx-proxy-le | 
nginx-proxy-le | 
nginx-proxy-le | 
```
Nothing useful here, so this PR just sends the output of `docker_exec` to `/dev/null`.

Silence docker_exec noisy output after #401

---

app/entrypoint.sh

In my opinion `set -x` makes the logs quite unreadable and is not of much help when trying to troubleshoot an issue. I'd rather remove it and work on cleaner and clearer debug logging.

Remove set -x for debug

---

.travis.yml
app/entrypoint.sh
app/letsencrypt_service

Only add actual links to the `SYMLINKED_DOMAINS` array instead of adding every file matching `/etc/nginx/certs/*.crt`

Only consider links in cleanup_links function

---

.travis.yml
test/tests/certs_san/run.sh
test/tests/certs_single/run.sh
test/tests/default_cert/run.sh
test/tests/docker_api/run.sh
test/tests/force_renew/run.sh
test/tests/symlinks/run.sh

This PR adds trapped cleanup functions to the test units, mostly useful when running the tests manually (without them, a lot of stuff have to be manually cleaned if a test stall and has to be killed).
+ fixes for a few typos / minor errors

Ci tests cleanup

---

.travis.yml
app/entrypoint.sh
app/functions.sh
app/letsencrypt_service
test/config.sh
test/run.sh
test/setup/setup-boulder.sh
test/setup/setup-nginx-proxy.sh
test/tests/certs_san/run.sh
test/tests/certs_single/run.sh
test/tests/docker_api/run.sh
test/tests/force_renew/run.sh
test/tests/permissions/expected-std-out.txt
test/tests/permissions/run.sh
test/tests/symlinks/run.sh
test/tests/test-functions.sh

This PR is a follow up to #412. It add checks and adjustment of ownership / permissions of sensitive files (private keys and ACME account keys) and enclosing folders + corresponding test unit.
The following files and folders are are currently adjusted by the PR:
```
[drwx------]  /etc/nginx/certs
├── [-rw-------]  default.key
├── [drwx------]  accounts
│   └── [drwx------]  acme-v01.api.letsencrypt.org
│       └── [drwx------]  directory
│           └── [-rw-------]  default.json
├── [drwx------]  domain.tld
│   └── [-rw-------]  key.pem
└── [drwx------]  subdomain.domain.tld
└── [-rw-------]  key.pem
```
I'm not sure yet about changing /etc/nginx/certs ownership and permissions, I suspect it might break things for people using host volumes.

Restrain permissions on sensitive files

---

.travis.yml
app/entrypoint.sh
app/functions.sh
app/letsencrypt_service
test/config.sh
test/tests/permissions/run.sh
test/tests/permissions_custom/expected-std-out.txt
test/tests/permissions_custom/run.sh
test/tests/permissions_default/expected-std-out.txt
test/tests/permissions_default/run.sh
test/tests/test-functions.sh

This PR introduces the following environment variables to provide control over ownership and permissions of the certificates and keys created by the container (+ the related Travis tests) :
* `FILES_UID` - Set the user owning the files and folders managed by the container. The variable can be either a user name if this user exists inside the container or a user numeric ID. Default to `root` (user ID `0`).
* `FILES_GID` - Set the group owning the files and folders managed by the container. The variable can be either a group name if this group exists inside the container or a group numeric ID. Default to the same value as `FILES_UID`.
* `FILES_PERMS` - Set the permissions of the private keys and ACME account keys. The variable must be a valid octal permission setting and defaults to `644`. …

Ownership and permissions configuration

---

app/letsencrypt_service
test/tests/symlinks/expected-std-out.txt
test/tests/symlinks/run.sh
test/tests/test-functions.sh

As discussed in #465, this PR should fix the remaining issues with hybrid configurations (certs obtained through the companion stored and used along certs obtained another way).
> [...] include a dot file next to the certs handled by the companion during creation / renewal (most importantly before the symlink cleanup function). Then the symlink cleanup function check for the presence of this dot file. If it's not there, those files are not handled by the companion, don't touch the symlinks.
@ejbp any thought before merging this ?

Follow certificates managed by the companion with a dot file

---

app/entrypoint.sh
app/functions.sh
app/letsencrypt_service

The DEBUG env var is actually case sensitive (eg it will work when set to `true` but not to `True` as it should). This PR makes it case insensitive.

Make the DEBUG env var case insensitive

---

Dockerfile
app/functions.sh
app/letsencrypt_service
test/tests/permissions_custom/run.sh
test/tests/permissions_default/run.sh

As brought up by @desimaniac in #471, the recent ownership and permissions configuration option (#463) did not change the symlinks ownership. This PR fix this to avoid confusion.

Change ownership of symlinks in addition to regular files

---

.gitignore
README.md
app/functions.sh
app/letsencrypt_service
app/letsencrypt_service_data.tmpl
test/config.sh
test/tests/container_restart/expected-std-out.txt
test/tests/container_restart/run.sh

This PR adds an additional functionality via an additional environmental variable.
Containers with the `LETSENCRYPT_RESTART_CONTAINER` variable set to true will be restarted when their respective certificates are updated/modified.
Fixes #434

New environmental variable LETSENCRYPT_RESTART_CONTAINER

---

README.md
app/letsencrypt_service
app/letsencrypt_service_data.tmpl
test/config.sh
test/setup/setup-boulder.sh
test/tests/certs_validity/expected-std-out.txt
test/tests/certs_validity/run.sh

This PR adds another environment variable called `LETSENCRYPT_MIN_VALIDITY`, that can be used to set the minimum validity of certificates per container.
Closes #477

Add LETSENCRYPT_MIN_VALIDITY variable

---

app/functions.sh

If the format of a CID source is unable to be matched, the next source should be tried.
Also try to exactly match 64bit alnum strings. Which should work be more robust against smaller format changes.
This should fix #514.

Correctly retry if format is not expected

---

docs/Basic-usage.md

I couldn't find anything about the syntax for multiple hosts. It is mentioned [here](https://github.com/jwilder/nginx-proxy#multiple-hosts), but I struggled anyway.

Add  a minor help on how to create certs for multiple hosts

---

install_simp_le.sh

Python 2.7 will reach its end of life on 1st Jan 2020.

Switch to Python 3

---

app/entrypoint.sh

This PR applies the same solution to the same issue as https://github.com/jwilder/nginx-proxy/pull/1213 and fixes #543 
Also `&disown` triggered ShellCheck, [with a suggestion to replace it with `& disown`](https://github.com/koalaman/shellcheck/wiki/SC1132#exceptions).

Fix DH parameters overwrite issue

---

app/functions.sh
test/config.sh
test/tests/location_config/expected-std-out.txt
test/tests/location_config/run.sh

This PR fixes #521 and adds a test unit specific to this issue.
In addition:
- `add_location_configuration` function was refactored and commented to be a bit easier to understand.
- `remove_all_location_configurations` function now use the simpler `[[ -e whatever ]] || continue` instead of `shopt -s nullglob` combined with `shopt` backup and restore.

 Use cp+rm / sed+cp+rm instead of mv / sed -i on location configuration

---

README.md
app/letsencrypt_service
docs/Advanced-usage.md
docs/Basic-usage.md
docs/Let's-Encrypt-and-ACME.md

As suggested in #525, this PR adds a `DEFAULT_EMAIL` environment variable to the `letsencrypt-nginx-proxy-companion` container that, if set, is used as a fallback when `LETSENCRYPT_EMAIL` isn't set on individual proxyed containers.
It also clarifies and warns about the incorrect behaviour of the `LETSENCRYPT_EMAIL` environment variable.

Add environment variable for global default email.

---

test/setup/setup-boulder.sh

Boulder master is currently broken on Docker : https://github.com/letsencrypt/boulder/issues/4284
This PR use the last tag before the commit that introduced that issue, instead of the `master` branch.

Fix CI breakage due to Boulder

---

app/nginx_location.conf

Issue #569. Simple change to ensure that auth_request is off for the acme challenge location, just as we do for auth_basic.

Set auth_request off for acme challenge location

---

app/functions.sh
test/tests/location_config/expected-std-out.txt
test/tests/location_config/run.sh

This PR is a fix for #561 
It makes the location configuration work as follow. Let say the domain is `foo.bar.baz.example.tld`:
- if a config file with the exact same name as your domain (`foo.bar.baz.example.tld`) is present, use it.
- else try every corresponding wildcard domain, from most qualified to least qualified, first ascending through the labels to the base domain (`*.bar.baz.example.tld`, `*.baz.example.tld`, `*.example.tld`) then descending (`foo.bar.baz.example.*`, `foor.bar.baz.*`, `foo.bar.*`, `foo.*`). The first matching config file will be used.
- if no wildcard location config file was found either, use the `default` location config file.

Enable use of wildcard location configurations

---

app/letsencrypt_service

This PR is a fix for #591, needed after the switch from ACME v1 accounts to ACME v2 accounts.

Verify files existence before perm check

---

README.md
docs/Container-configuration.md
docs/Let's-Encrypt-and-ACME.md
docs/Persistent-data.md
docs/Standalone-certificates-(beta).md

This PR brings the documentation in line with the changes made by the switch from ACME v1 to ACME v2 protocol support.

Update doc to reflect ACME v2 changes

---

.travis.yml

This PR fixes Travis Build config validation's warning and informations.

Remove deprecated keys / aliases from .travis.yml

---

Dockerfile

`golang` bumped to `1.14-alpine`
`alpine` bumped to `3.11`

Upgrade golang build stage and alpine image

---

install_simp_le.sh

Updated simp_le tagged version to include fix for Buypass CA. Fixes issue https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues/634

Update simp_le to 0.18.0

---

app/letsencrypt_service_data.tmpl
test/config.sh
test/tests/networks_segregation/expected-std-out.txt
test/tests/networks_segregation/run.sh

Hi, @buchdag!
This pull-request implements the discussion we've started in #571
I've introduced a new env variable for LE container `MUST_BE_CONNECTED_WITH_NETWORK`, that limits the LE scope to containers, included only in the specified network. The tests are included.
Could you review this pull request, please? If it seems acceptable to you, I will add the necessary documentation. Thank you!

Implemented segregation by network

---

.travis.yml

Travis CI changed its pricing model, OSS builds are no longer free: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
This commit greatly reduce credit consumption by building only on one Linux distro (Ubuntu 20.04), instead of three previously.
The next move will either be obtaining free monthly credit from Travis CI or moving to GitHub actions.

Travis CI is no longer free for OSS

---

app/start.sh
test/setup/setup-nginx-proxy.sh
test/tests/container_restart/run.sh
test/tests/default_cert/run.sh
test/tests/test-functions.sh

This PR does two things motsly aimed at speeding up tests:
- It makes `docker-gen`'s `--wait` argument user configurable via an environment variable (`DOCKER_GEN_WAIT`) and lower the default from a **minimum wait of 15 seconds** after container change events to a more reasonable 500 milliseconds. `--wait` was only supposed to act as debounce, and 15 seconds is pretty long for a debounce.
- It uses more agressive polling in the tests and fix the timeouts so that they're based on real elapsed time and not on the number of iterations through the loop.
This saves roughly another 20% of build time on Travis CI.

Speed up tests execution.

---

app/letsencrypt_service

I was trying the ZeroSSL support and the API key wasn't picked up properly by the letsencrypt container, which had me scratching my head.
I found out that setting `ZEROSSL_API_KEY` directly on the letsencrypt container wasn't supported (the docs aren't clear about this), this pull request tries to fix this.
By the way, thanks for all the work, it is much appreciated!

Allow ZEROSSL_API_KEY on the letsencrypt container

---

Dockerfile

The volumes on the Dockerfile were parts of my early work on the transition to `amce.sh` and should not have made their way in #719 as they prevent detection of missing volumes by the `check_writable_directory()` tests in the entrypoint script.

Remove default volumes from Dockerfile

---

Dockerfile

Now that we use GitHub's dependabot we can and should update dependencies more often.

Use patch level releases in Dockerfile's FROM

---

app/cleanup_test_artifacts
app/functions.sh
test/tests/location_config/run.sh

Matching globs are common because the script runs in the certs
directory.
The test uses a suffix match as the test domains don't include
subdomains, although such cases should probably be considered.
Fix the le3.wtf test. The existing add_location_configuration modifies
"default"; a second add is not necessary.
Fixes #763

Fix unintentional file globbing during wildcard lookup

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/workflows/test.yml
README.md
app/entrypoint.sh
app/letsencrypt_service
docs/Advanced-usage.md
docs/Basic-usage.md
docs/Container-configuration.md
docs/Container-utilities.md
docs/Docker-Compose.md
docs/Getting-containers-IDs.md
docs/Invalid-authorizations.md
docs/Let's-Encrypt-and-ACME.md
docs/Persistent-data.md
docs/Standalone-certificates.md
docs/Zero-SSL.md
test/README.md
test/run.sh
test/setup/docker-gen/Dockerfile
test/setup/nginx-proxy/Dockerfile
test/setup/setup-nginx-proxy.sh
test/tests/certs_san/run.sh
test/tests/certs_single_domain/run.sh
test/tests/certs_standalone/run.sh
test/tests/docker_api/run.sh
test/tests/test-functions.sh

This PR handles the renaming of the project to `nginx-proxy/acme-companion` (#768) and the use of the new DockerHub registry namespace [`nginxproxy`](https://hub.docker.com/u/nginxproxy) for the images.

Projects name change

---

docs/Advanced-usage.md
docs/Docker-Compose.md
docs/Invalid-authorizations.md
test/setup/docker-gen/Dockerfile
test/setup/nginx-proxy/Dockerfile
test/setup/setup-nginx-proxy.sh

This PR follows the renaming of `ninx-proxy`'s default branch from `master` to `main`.

chore: nginx-proxy default branch renamed to main

---

docs/Advanced-usage.md

A \ was missing so pasting resulted in premature and incomplete execution.

Fix small missing \ to make it copy pasteable

---

docs/Let's-Encrypt-and-ACME.md

Useful but undocumented environment variable to avoid setting `LETSENCRYPT_KEYSIZE` on every container manually

Add `DEFAULT_KEY_SIZE` variable to the documentation

---

Dockerfile

Self explanatory.
Should fix a bug that prevented upgrade of the `alpine` version.

Bump acme.sh version to 2.9.0

---

app/letsencrypt_service
app/letsencrypt_service_data.tmpl

This PR fixes #761 and prevents other errors of the same type.
Because white space trimming and default empty value are now done in the template, it simplifies variable checks in the service loop.

Trim whitespaces from environment variables

---

.github/workflows/dockerhub.yml
.github/workflows/test.yml
test/setup/setup-boulder.sh
test/setup/setup-local.sh

This fix the two `ocsp_must_staple` tests that rely on Boulder rather than Pebble.

ci: fix boulder integration tests

---

app/letsencrypt_service

A possible fix for https://github.com/nginx-proxy/acme-companion/issues/975
It is working for my use case, please check I didn't break something else.

check EAB_KID and HMAC_KEY before registering the ACME account

---

app/functions.sh
app/letsencrypt_service
docs/Persistent-data.md
test/tests/permissions_custom/run.sh
test/tests/permissions_default/run.sh

fix: restrict private key permissions

---

.github/dependabot.yml

This PR add GitHub Actions ecosystem to Dependabot.

ci: add GitHub Actions to Dependabot config

---

docs/Standalone-certificates.md

I think that the docs can be slightly clarified to avoid misunderstandings like in #1044

Clarify documentation configuration requirements for standalone certificates

---

.github/workflows/test.yml
.gitignore
app/entrypoint.sh
app/functions.sh
docs/Advanced-usage.md
docs/Docker-Compose.md
docs/Getting-containers-IDs.md
test/config.sh
test/setup/setup-local.sh
test/setup/setup-nginx-proxy.sh
test/tests/docker_api_legacy/run.sh
test/tests/test-functions.sh

This PR basically rename the old `com.github.jrcs.letsencrypt_nginx_proxy_companion.x` labels to `com.github.nginx-proxy.x` labels, while keeping backward compatibility with the legacy labels.

refactor: move to correctly namespaced labels

---

test/setup/setup-boulder.sh

Attempt to fix the failing OCSP test, which are the only ones that rely on Boulder rather than Pebble.

test: bump boulder to release-2023-12-04

---

app/functions.sh

This pull request fixes two issues in `enumerate_wildcard_locations` function:
1) When a wildcard domain passed to the function, it never returns. Even though wildcard domains are not supported at the moment, I think, infinite loop should be fixed. Currently any wildcard domain in any container configuration completely hangs the service. 
2) In `descending_wildcard_locations` the first occurrence of `last_label` was removed, which might generate wrong wildcards:
```bash
#!/bin/bash
source ./functions.sh
enumerate_wildcard_locations test.com.example.com
```

fix: prevent infinite loop in enumerate_wildcard_locations

---

docs/Docker-Compose.md

In the [Advanced Usage doc](https://github.com/nginx-proxy/acme-companion/blob/main/docs/Advanced-usage.md#step-2---docker-gen), the there is `5s:30s` specified after `-wait`. In this doc it was missing. For completeness I have added it here.

add 5s:30s to -wait

---

test/tests/location_config/expected-std-out.txt
test/tests/location_config/run.sh

Update tests for the regression fixed in #1064

test: update wildcard location enumeration test

---

app/letsencrypt_service
test/tests/symlinks/run.sh

If `default.crt` / `default.key` were symlinks to certificates managed by this container, they were removed along other symlinks in `/etc/nginx/certs`. This was an unintentional behaviour.

fix: dot not remove symlinked default certificate / private key

---

app/cert_status

fix: don't display LE certificate as erroneously expired

---

Dockerfile
app/letsencrypt_service
install_acme.sh
test/tests/acme_accounts/run.sh
test/tests/acme_eab/run.sh

Redo of #1063 with fixes.
Fixes #1035

build: acme.sh 2.9.0 -> 3.0.4

---

Dockerfile
app/letsencrypt_service

The PR customise the user agent string provided by acme.sh, adding the acme-companion version.

build: use custom user agent string

---

.github/workflows/test.yml

The instability with version 4 of `actions/upload-artifact` and `actions/download-artifact` should be fixed by now.

ci: bump artifact actions  from 3 to 4

---

app/letsencrypt_service_data.tmpl

This is a proposed fix for #1049. It orders the containers being iterated over by descending creation timestamp (most recent first) instead of by ascending certificate domain name.
Closes #1049

fix: handle most recently created containers first

---

app/functions.sh

With cgroup v2, CID can be read from /proc/self/mountinfo
OCI specification defines that hostname must be set with UTS namespace.
http://wking.github.io/opencontainer-runtime-spec/#_hostname
Podman set the hostname of container running in a pod to a name of pod, e.g. 'test-pod', not a container ID, e.g. '1cb364360e42'.
Docker API via /tmp/docker.sock linked to /var/run/podman.sock returns error as following.
{"cause":"no such container","message":"\"test-pod\" is a pod, not a container: no such container","response":404}
Need to get container ID from /proc/self/mountinfo from the container inside if the container is running in a pod by Podman.

fix: get container ID from /proc/self/mountinfo (for podman)

---

.github/workflows/test.yml
test/config.sh
test/setup/pebble/.env
test/setup/pebble/docker-compose.yml
test/setup/pebble/pebble-config-eab.json
test/setup/pebble/pebble-config.json

New versions of Pebble are available from ghcr.io only.
Version 2.5.x support OCSP stapling, removing the need to use Boulder in CI for this specific test.

test: upgrade pebble to 2.5.2

---

test/setup/pebble/.env

Not much to see here, just bumping the Pebble version used in tests.

test: use Pebble 2.6.0

---

.shellcheckrc
README.md
app/letsencrypt_service
app/letsencrypt_service_data.tmpl
app/start.sh
docs/Basic-usage.md
docs/Let's-Encrypt-and-ACME.md

This PR pick up the work done by @daweedm in #1022 ( thanks 👍 )
I tested it with Gandi Live DNS, seems to work without issue.
@pini-gh I know you worked on a DNS-01 fork too, so a review would be welcome.
Ideally I'd also like this to include wildcard certificate compatibility before merge.

feat: DNS-01 challenge support

---

test/setup/pebble/docker-compose.yml
test/setup/pebble/setup-pebble.sh
test/setup/setup-boulder.sh
test/setup/setup-local.sh

This PR fix invocation of docker compose in the test scripts.

tests: fix docker compose use

---

docs/Google-Trust-Services.md
docs/README.md

Add basic details on using the GTS ACME endpoint.

docs: add Google Trust Services instructions

---

app/entrypoint.sh

As discussed here: https://github.com/nginx-proxy/acme-companion/issues/1054
If socket is not readable, for example when protected with SELinux and/or run as a rootless user, the existing error is deceptive. An additional error to check that it is readable before checking if it is a socket will clarify the problem. SELinux tip included for good measure.

feat: specific error for socket permission

---

Dockerfile
docs/Let's-Encrypt-and-ACME.md

This PR bump acme.sh to version `3.0.9`

build: bump acme.sh to 3.0.9

---

docs/Standalone-certificates.md

As discussed. Added a little more detail into the standalone configuration doc to be more specific around what is required when defining a specific DNS API configuration for a standalone cert.

Docs: Clarify standalone dns01 API configuration structure with example

---

app/entrypoint.sh

Warn instead of exiting when `/usr/share/nginx/html` directory is not accessible.
Fixes #1159

fix: stop enforcing html directory

---

README.md
docs/Basic-usage.md

I'm in the middle of setting this up and was a bit confused by the README.md being a bit ambiguous about volume count. In some places it refers to there being three required volumes, but the subsequent example shows only two.
I found this commit [28bdc6b8](https://github.com/nginx-proxy/acme-companion/commit/28bdc6b8322d8b199e47aa5a34b345ad65182d71) that removes the third volume and changes the language to refer to _two volumes_.
My conclusion is: there should be two volumes and there's been an editing mistake. This MR is just to fix the forgotten references to three volumes. _I did NOT try to understand how anything works or WHY there is only two now._
((I don't think i've made an MR like this before. Should i have made an issue first?))

docs: specify correct amount of volumes

---

app/entrypoint.sh

Fix proposed by @andrei-datcu for #1179 
The entrypoint will fail if `test -S $socket_file` is `false` but only display a warning if `test -r $socket_file` is `false`.

fix: reverse docker socket test

---

docs/Hooks.md

Fix a typo in the description of Le_PostHook.

docs: typo in hooks documentation

---

Dockerfile

Add [`syntax`](https://docs.docker.com/reference/dockerfile/#syntax) parser directive to the first line of the [Dockerfile](https://docs.docker.com/reference/dockerfile/).
To declare the Dockerfile syntax version to use for the build.
If unspecified, [BuildKit](https://docs.docker.com/build/buildkit/) uses a bundled version of the Dockerfile frontend.
Append `# syntax=docker.io/docker/dockerfile:1` to the top of the [Dockerfile](https://docs.docker.com/reference/dockerfile/).

build: add `syntax` parser directive to Dockerfile

---

docs/Docker-Compose.md

1. 'version' is obsolete.
2. Connect to default bridge is not recommended, just let docker create a 'nginx-proxy_default' bridge by default, or define named network.

Remove version and default bridge network

---

docs/Let's-Encrypt-and-ACME.md

LetsEncrypt no longer sends Certificate Expiration mails.
https://letsencrypt.org/2025/01/22/ending-expiration-emails

docs: Update LETSENCRYPT_EMAIL description
