nginx-proxy/acme-companion

app/letsencrypt_service
Reverts JrCs/docker-letsencrypt-nginx-proxy-companion#140
=> Revert "[FEATURE] Create SAN certificates only for common domains"

README.md
Hi JRCS,
Thank you for your excellent work on this image. I've been having a bit of trouble with it lately, but these examples were instrumental in solving my problems and I think it would be a good idea to include them in the readme. 
Regards,
=> Additional examples 

README.md, app/letsencrypt_service
Adds a new env variable ACME_TOS_HASH to support other CA´s ACME implementation.
=> Support for alternative TOS hashes

README.md
Created a simple docker-compose example repo based on your feedback here #208.
=> Add a link to Dmitry's docker-compose example.

install_simp_le.sh
This has been written with some help from https://stackoverflow.com/a/19048754/1959568
I suggest to squash the commits, as the second description is misleading and should read something like *update dependencies and installation flow for simp_le, avoiding virtualenv*.
=> install simp_le from master branch + make that work, fixes #221

install_simp_le.sh
This is a concurrent approach to #227 for discussion and evaluation reasons.
=> use tagged 0.3.0 simp_le release

install_simp_le.sh
=> bump simp_le to 0.4.0 (acme 0.16)

install_simp_le.sh
[+ a workaround for some installation problems caused by a bug in pip](https://github.com/zenhack/simp_le#051)
=> Bump simp_le to 0.5.1 (acme 0.17)

README.md
Example that shows how to integrate Jenkins with Nginx/Nginx-proxy and Let's Encrypt. It also describes how to test things locally with ngrok.io
=> Added jenkins nginx letsencrypt example

app/letsencrypt_service
=> fixes #311 by making account_key_dir into a relative link.

Dockerfile, app/start.sh
Two small changes: the image has been updated to Alpine 3.7 and now stop with a 0 exit status.
=> Merge dev into master

app/functions.sh, app/letsencrypt_service
I added log error if nginx-proxy is not run,  and i modified function docker_exec in case if docker can not create exec comand.
=> Log error if nginx-proxy is not run

README.md
=> Warn about ACME v2 not being supported in README

install_simp_le.sh
Fix an installation bug with pip.
=> Update simp_le to 0.9.0

app/signal_le_service
=> Remove old procps specific pkill command

test/config.sh, test/tests/force_renew/expected-std-out.txt, test/tests/force_renew/run.sh, test/tests/test-functions.sh
This PR adds a test unit for the /app/force_renew script. Pretty straightforward.
=> Add a test unit for /app/force_renew

install_simp_le.sh
=> Update simp_le to 0.10.0

install_simp_le.sh
=> Update simp_le to 0.11.0

test/setup/setup-local.sh
credits to @Greek64 for finding and solving the bug in #482
=> Fix local test suite

install_simp_le.sh
=> Update simp_le to 0.12.0

.travis.yml
Test suite docker-compose version bump to `1.23.2`
=> Update docker-compose in test suite

Dockerfile
=> Update build stage to golang 1.11

docs/Let's-Encrypt-and-ACME.md
=> [skip ci] Update test certificate doc

README.md
adding missed " \"  ### Step 3 - proxyed container(s) after ```---name your-proxyed-app```
=> fix syntax in step 3

install_simp_le.sh
=> Update simp_le to 0.14.0

Dockerfile
=> Update build stage to golang 1.12

Dockerfile
=> Upgrade image to alpine 3.9

.travis.yml, test/run.sh, test/tests/certs_san/run.sh, test/tests/certs_single/run.sh, test/tests/certs_validity/run.sh, test/tests/container_restart/run.sh, test/tests/default_cert/run.sh, test/tests/force_renew/run.sh, test/tests/location_config/run.sh, test/tests/permissions_custom/run.sh, test/tests/permissions_default/run.sh, test/tests/symlinks/run.sh, test/travis/containers-logs.sh, test/travis/update-docker-compose.sh
This PR only concerns the test suite.
It adds Ubuntu 16.04 Xenial and Ubuntu 18.04 Bionic to the test matrix, move the update of Travis's `docker-compose` to its own separate script and fixes the display of Docker containers logs when the build fails.
=> Test suite update

Dockerfile
=> Upgrade image to alpine 3.10

README.md, app/entrypoint.sh, app/functions.sh, app/letsencrypt_service, install_simp_le.sh, test/setup/setup-boulder.sh, test/tests/permissions_custom/run.sh, test/tests/permissions_default/run.sh, test/tests/test-functions.sh
The PR switch from ACME v1 to ACME v2 protocol support using version `0.16.0` of `simp_le`.
=> Switch to ACME v2

README.md, docs/Let's-Encrypt-and-ACME.md
=> Multi-domains certificates examples

app/cert_status, app/entrypoint.sh, app/force_renew, app/functions.sh, app/letsencrypt_service, app/start.sh
=> Shellcheck linting

app/letsencrypt_service_data.tmpl, docs/Let's-Encrypt-and-ACME.md, test/config.sh, test/tests/certs_single_domain/expected-std-out.txt, test/tests/certs_single_domain/run.sh
This PR replaces #610. This one is based on the `master` branch.
=> Implemented LETSENCRYPT_SINGLE_DOMAIN_CERTS environment variable

.gitignore, app/entrypoint.sh, app/functions.sh, app/letsencrypt_service, app/start.sh, docs/README.md, docs/Standalone-certificates.md, test/config.sh, test/setup/setup-nginx-proxy.sh, test/tests/certs_standalone/expected-std-out.txt, test/tests/certs_standalone/run.sh
See #368 for discussion about this feature.
Instructions are here : https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/dev/docs/Standalone-certificates.md
=> Merge standalone certificate feature to master

app/letsencrypt_service_data.tmpl, test/tests/certs_san/expected-std-out.txt, test/tests/certs_san/run.sh, test/tests/test-functions.sh
=> Trim trailing dot from domains

app/functions.sh, test/tests/certs_standalone/expected-std-out.txt, test/tests/certs_standalone/run.sh, test/tests/test-functions.sh
This PR tests for and fixes #674
=> Don't incorrectly grep existing subdomain with add_standalone_configuration()

Dockerfile
=> Update build stage to golang 1.15

app/functions.sh
Search in all .conf files for the server configuration when a standalone configuration exists and not just in default.conf,
=> Search in all config files for standalone config

Dockerfile
This PR update the internal ACME client to the latest new patch version.
=> Update acme.sh to 2.8.8

docs/Basic-usage.md
Document now points to correct location of data persistence
=> Fix document location

README.md
Trivial change to readme to fix broken link.
=> Fix broken data persistence link in README.md

README.md, docs/Advanced-usage.md, docs/Basic-usage.md, docs/Container-configuration.md, docs/Persistent-data.md, docs/Standalone-certificates.md
Use named volume on all example and discourage use of anonymous volumes.
It was confusing that the doc recommended using named volume yet used anonymous volumes in the examples.
=> Update volume related docs and examples

.github/workflows/test.yml
This PR enables the on demand dispatch of the tests workflow.
=> Enable workflow_dispatch on tests

Dockerfile
=> Bump dockergen version from 0.7.6 to 0.8.0

.dockerignore, Dockerfile
See the relevant discussion: https://github.com/nginx-proxy/nginx-proxy/pull/1444#discussion_r820956080
=> Include license in Docker image

Dockerfile
to build with podman / buildah.
=> build: disambiguate base image names

Dockerfile, docs/Let's-Encrypt-and-ACME.md
Bump acme.sh to [3.1.0](https://github.com/acmesh-official/acme.sh/releases/tag/3.1.0)
=> build: bump acme.sh to 3.1.0

Dockerfile, docs/Let's-Encrypt-and-ACME.md
This PR bump acme.sh to version `3.1.1`
=> build: bump acme.sh to 3.1.1
